Physik & Schulhaus
Willibald-Gluck-Gymnasium/wgg-homepage pull request #62
Opened 2022-05-20 13:26 UTC by ScriptorGames

2022-05-20 14:52 UTC, Erdragh approved these changes
Problem:
Link ohne Ziel zu "questionair". Hierzu hast du ja extra #60 geöffnet, bis das resolved ist, wird dieser Link halt nirgendwo hin führen.

In der Interesse daran, dass du nächsten Freitag möglichst reibungslos weiterarbeiten kannst approve ich diese PR und merge sie, aber vergiss nicht die Änderungen, die aus #60 hervorgehen, später noch einzureichen!

2022-05-20 14:52 UTC, Erdragh commented on resources/content/articles/physik_grav.html
> +    <v-image name="grav_schueler1" alt="Foto 1" />
v-image sollte eigentlich nicht in paragraphen sein, es sei denn dies hat einen bestimmten Grund?

2022-05-20 14:56 UTC, Erdragh requested changes
Die Checks failen, aber ich weiß nicht warum, da ich das System nicht programmiert habe.

2022-06-26 13:47 UTC, alexanderhorner commented
Du kannst die Test auch lokal ausführen, du musst nicht jedes Mal pushen um zu sehen ob's klappt. In der Konsole einfach `npm run article-test`

2022-06-26 13:48 UTC, alexanderhorner commented
Außerdem die Artikel links bitte so ausführlich sir möglich lassen. Am besten einfach den Titel nehmen und bisschen Link freundlich gestalten (also - statt lehrreichen z.B.). Das reicht vollkommen aus.

2022-10-04 11:37 UTC, closed without merging